version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
      - npm i -g pm2
  build:
    commands:
      - echo Building files
      - npm run build
      - rm -rf node_modules
      - pm2-runtime start ecosystem.config.js
artifacts:
  files:
    - '**/*'
  base-directory: '.'
  discard-paths: no
